# Generated by Django 4.2.28 on 2026-02-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255)),
                ('common_name_zh', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='plants/')),
                ('tcm_info', models.TextField(blank=True)),
                ('feng_shui_info', models.TextField(blank=True)),
                ('festive_info', models.TextField(blank=True)),
            ],
        ),
    ]
